import { createElement } from "lwc";
import MyFirstComponent from "c/myFirstComponent";

describe("c-my-first-component", () => {
  let element;
  beforeEach(() => {
    // Arrange
    element = createElement("c-my-first-component", {
      is: MyFirstComponent
    });

    // Act
    document.body.appendChild(element);
  });

  afterEach(() => {
    // The jsdom instance is shared across test cases in a single file so reset the DOM
    while (document.body.firstChild) {
      document.body.removeChild(document.body.firstChild);
    }
  });

  it("TODO: test case generated by CLI command, please fill in test logic", () => {
    // Assert
    expect(1).toBe(1);
  });

  test("should display the first message", () => {
    const firstDiv = element.shadowRoot.querySelector("div.first");

    // Assert
    expect(firstDiv.textContent).toBe("Hello, World!");
  });

  test("should display the second message", () => {
    const secondDiv = element.shadowRoot.querySelector("div.second");

    // Assert
    expect(secondDiv.textContent).toBe("My greeting is: World.");
  });
});
